config/routes.rb
Rails.application.routes.draw do

  root to: "homes#index"
  get 'admins' => 'admins#index', :as => 'admin_root'

  devise_for :users, controllers: {sessions: "users/sessions"} do
    delete 'users/sign_out/:auth_token' => 'sessions#destroy', :as => :destroy_user_session
    get "sign_in" => "sessions#create" # for testing
  end

  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }

  resources :homes

  resources :admins
  namespace :admin do    
    resources :admins
    resources :users
    resources :notes do 
      resources :note_details
    end
    resources :product_types
    resources :products
    resources :photo_sliders
  end

end

app/models/photo_slider.rb
class PhotoSlider < ActiveRecord::Base
    has_attached_file :image, :styles => { :display => "763x419#", :thumb => "260x190#" }, :default_url => "no-image.jpg",
			:url => '/images/photo/:basename_:style_:id.:extension',
			:path => ":rails_root/public/images/photo/:basename_:style_:id.:extension"

	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/admin/photo_sliders_controller.rb
class Admin::PhotoSlidersController < ApplicationController
	before_filter :authenticate_admin!
	layout "admin"

	def index	
		@photo_sliders = PhotoSlider.all
		#render json: @photo_slider
	end

	def show
	    @photo_slider = PhotoSlider.find(params[:id])

	    respond_to do |format|
	      format.html # show.html.erb
	      format.json { render json: @photo_slider }
	    end
	end

	def new
	    @photo_slider = PhotoSlider.new

	    respond_to do |format|
	      format.html # new.html.erb
	      format.json { render json: @photo_slider }
	    end
	end

	def create
	    @photo_slider = PhotoSlider.new(photo_slider_params)

	    respond_to do |format|
	      if @photo_slider.save
	        format.html { redirect_to [:admin,@photo_slider], notice: 'Photo Slider was successfully created.' }
	        format.json { render json: @photo_slider, status: :created, location: @photo_slider }
	      else
	        format.html { render action: "new" }
	        format.json { render json: @photo_slider.errors, status: :unprocessable_entity }
	      end
	    end
	end

	def edit
	    @photo_slider = PhotoSlider.find(params[:id])
	end

	def update
		@photo_slider = PhotoSlider.find(params[:id])		

	    respond_to do |format|
	      if @photo_slider.update_attributes(photo_slider_params)
	        format.html { redirect_to [:admin,@photo_slider], notice: 'Photo Slider was successfully updated.' }
	        format.json { head :no_content }
	      else
	        format.html { render action: "edit" }
	        format.json { render json: @photo_slider.errors, status: :unprocessable_entity }
	      end
	    end
	end

	def destroy
	    @photo_slider = PhotoSlider.find(params[:id])
	    @photo_slider.destroy

	    respond_to do |format|
	      format.html { redirect_to admin_photo_sliders_url }
	      format.json { head :no_content }
	    end
	  end

	private
	
	def photo_slider_params
	    params.require(:photo_slider).permit(:tittle, :description, :image,)
	end
end

app/helpers/admin/photo_sliders_helper.rb
module Admin::PhotoSlidersHelper
end

app/views/admin/photo_sliders/_form.html.erb
<%= form_for([:admin, @photo_slider], html: {class: "form-horizontal"}) do |f| %>
  <% if @photo_slider.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo_slider.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if params[:action] == "new" %>
    <%= f.hidden_field :created_by, :value => current_admin.id %>
  <% else %>
    <%= f.hidden_field :updated_by, :value => current_admin.id %>
  <% end %>

  <div class="form-group">
    <label class="col-sm-3 control-label">
      Tittle
    </label>
    <div class="col-sm-7">
      <%= f.text_field :tittle, class: 'form-control', placeholder: 'Enter tittle ..' %>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-3 control-label">
      Description
    </label>
    <div class="col-sm-7">
      <%= f.text_field :description, class: 'form-control', placeholder: 'Enter tittle ..' %>
    </div>
  </div>  

  <div class="form-group">
    <label class="col-sm-3 control-label">
      Photo Slider
    </label>
    <div class="col-sm-7">
      <%= f.file_field :image, :style => "width:360px", :class => "form-control" %>
    </div>
  </div>

  <%= f.hidden_field :user_id, :value => current_admin.id %>  

  <div class="form-group">
    <div class="col-sm-7">
      <button type="submit" class="btn btn-o btn-primary">
        Submit
      </button>

      &nbsp; &nbsp; &nbsp;
      <button class="btn" type="reset">
          <i class="icon-undo bigger-110"></i>
          Reset
      </button>
    </div>

  </div>
<% end %>

<%= content_for :css do %>
  
    <!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->
    <link href="/vendor/bootstrap-touchspin/jquery.bootstrap-touchspin.min.css" rel="stylesheet" media="screen">
    <link href="/vendor/select2/select2.min.css" rel="stylesheet" media="screen">
    <link href="/vendor/bootstrap-datepicker/bootstrap-datepicker3.standalone.min.css" rel="stylesheet" media="screen">
    <link href="/vendor/bootstrap-timepicker/bootstrap-timepicker.min.css" rel="stylesheet" media="screen">
    <!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->
<% end %>

<%= content_for :js do %>
    
    <!-- start: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
    <script src="/vendor/ckeditor/ckeditor.js"></script>
    <script src="/vendor/ckeditor/adapters/jquery.js"></script>
    <script src="/vendor/jquery-validation/jquery.validate.min.js"></script>

    <script src="/vendor/maskedinput/jquery.maskedinput.min.js"></script>
    <script src="/vendor/bootstrap-touchspin/jquery.bootstrap-touchspin.min.js"></script>
    <script src="/vendor/autosize/autosize.min.js"></script>
    <script src="/vendor/selectFx/classie.js"></script>
    <script src="/vendor/selectFx/selectFx.js"></script>
    <script src="/vendor/select2/select2.min.js"></script>
    <script src="/vendor/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
    <script src="/vendor/bootstrap-timepicker/bootstrap-timepicker.min.js"></script>
    <!-- end: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
  
    <!-- start: JavaScript Event Handlers for this page -->
    <script src="/assets/js/form-validation.js"></script>
    <script src="/assets/js/form-elements.js"></script>
    <script>
      jQuery(document).ready(function() {
        Main.init();
        FormValidator.init();
        FormElements.init();
      });
    </script>
<% end %>

app/views/admin/photo_sliders/edit.html.erb
<div class="wrap-content container" id="container">
  <!-- start: PAGE TITLE -->
  <section id="page-title">
    <div class="row">
      <div class="col-sm-8">
        <h1 class="mainTitle">Form Edit Photo Slider</h1>
      </div>
      <ol class="breadcrumb">
        <li>
          <span>Photo Slider Forms</span>
        </li>
        <li class="active">
          <span>Form Photo Slider</span>
        </li>
      </ol>
    </div>
  </section>
  <!-- end: PAGE TITLE -->
  <!-- start: BASIC EXAMPLE -->
  <div class="container-fluid container-fullw bg-white">
    <div class="row">
      <div class="col-md-12">
        <div class="row">
          <div class="col-lg-8 col-md-12">
            <div class="panel panel-white">
              <div class="panel-heading">
                <h5 class="panel-title">Form Edit</h5>
              </div>
              <div class="panel-body">
                <%= render "form" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12 space20">
        <a href="/admin/photo_sliders" class="btn btn-info">
          Back <i class="fa fa-reply"></i>
        </a>
      </div>
    </div>
  </div>
  <!-- end: BASIC EXAMPLE -->
</div>

app/views/admin/photo_sliders/index.html.erb
<div class="wrap-content container" id="container">
<!-- start: PAGE TITLE -->
<section id="page-title">
  <div class="row">
    <div class="col-sm-8">
      <h1 class="mainTitle">PHOTO SLIDER LIST</h1>
      <span class="mainDescription"></span>
    </div>
    <ol class="breadcrumb">
      <li>
        <span>Dashboard</span>
      </li>
      <li class="active">
        <span>Photo Slider List</span>
      </li>
    </ol>
  </div>
</section>
<!-- end: PAGE TITLE -->            

<div class="clearfix">&nbsp;</div>

<!-- start: DYNAMIC TABLE -->
<div class="container-fluid container-fullw">
  <div class="row">
    <div class="col-md-12">
      <h5 class="over-title margin-bottom-15">List of <span class="text-bold">PHoto Slider</span></h5>
      <div class="row">
        <div class="col-md-6 space20">
          <a href="/admin/photo_sliders/new" class="btn btn-green">
            Add New <i class="fa fa-plus"></i>
          </a>                      
        </div>
      </div>
      <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover table-full-width dataTable no-footer" id="sample_1">
          <thead>
            <tr>
                <th>Tittle</th>
                <th>Description</th>
                <th>Image</th>
                <th>Action</th>                
            </tr>
          </thead>
          <tbody>
            <% @photo_sliders.each do |photo_slider| %>
              <tr class="note-content-table">
                <td><%= photo_slider.tittle %></td>                
                <td><%= photo_slider.description %></td>                
                <td><img class="transparent-logo" src="<%= photo_slider.image.url(:thumb) %>" alt="Boutique"></td>                
                <td>
                <a href="<%= admin_photo_slider_path(photo_slider) %>" class="btn btn-xs btn-default">
                  Show
                </a>
                <a href="<%= edit_admin_photo_slider_path(photo_slider) %>" class="btn btn-xs btn-default">
                  Edit
                </a>

                <a data-confirm="Are you sure?" data-method="delete" href="<%= admin_photo_slider_path(photo_slider) %>" class="btn btn-xs btn-danger" rel="nofollow">
                  Delete
                </a>
              </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
</div>

<%= content_for :css do %>
<!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->
<link href="/vendor/bootstrap-touchspin/jquery.bootstrap-touchspin.min.css" rel="stylesheet" media="screen">
<link href="/vendor/select2/select2.min.css" rel="stylesheet" media="screen">
<link href="/vendor/bootstrap-datepicker/bootstrap-datepicker3.standalone.min.css" rel="stylesheet" media="screen">
<link href="/vendor/bootstrap-timepicker/bootstrap-timepicker.min.css" rel="stylesheet" media="screen">
<link href="/vendor/DataTables/css/DT_bootstrap.css" rel="stylesheet" media="screen">
<!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->
<% end %>

<%= content_for :js do %>
<!-- start: JavaScript Event Handlers for this page -->
<script src="/vendor/maskedinput/jquery.maskedinput.min.js"></script>
<script src="/vendor/bootstrap-touchspin/jquery.bootstrap-touchspin.min.js"></script>
<script src="/vendor/autosize/autosize.min.js"></script>
<script src="/vendor/selectFx/classie.js"></script>
<script src="/vendor/selectFx/selectFx.js"></script>
<script src="/vendor/select2/select2.min.js"></script>
<script src="/vendor/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
<script src="/vendor/bootstrap-timepicker/bootstrap-timepicker.min.js"></script>
<!-- end: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
<!-- start: JavaScript Event Handlers for this page -->
<script src="/assets/js/form-elements.js"></script>
<script src="/vendor/DataTables/jquery.dataTables.min.js"></script>
<script src="/assets/js/table-data.js"></script>
<script>
    jQuery(document).ready(function() {
        Main.init();
        TableData.init();
        FormElements.init();
    });
</script>
<!-- end: JavaScript Event Handlers for this page -->
<% end %>

app/views/admin/photo_sliders/new.html.erb
<div class="wrap-content container" id="container">
	<!-- start: PAGE TITLE -->
	<section id="page-title">
		<div class="row">
			<div class="col-sm-8">
				<h1 class="mainTitle">Form Tambah Photo Slider</h1>
				<span class="mainDescription">Form untuk menambah data Photo Slider yang baru</span>
			</div>
			<ol class="breadcrumb">
				<li>
					<span>Photo Slider Forms</span>
				</li>
				<li class="active">
					<span>Form Photo Slider</span>
				</li>
			</ol>
		</div>
	</section>
	<!-- end: PAGE TITLE -->
	<!-- start: BASIC EXAMPLE -->
	<div class="container-fluid container-fullw bg-white">
		<div class="row">
			<div class="col-md-12">
				<div class="row">
					<div class="col-lg-8 col-md-12">
						<div class="panel panel-white">
							<div class="panel-heading">
								<h5 class="panel-title">Form Tambah</h5>
							</div>
							<div class="panel-body">
								<%= render "form" %>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="row">
            <div class="col-md-12 space20">
              <a href="/admin/photo_sliders" class="btn btn-info">
                Back <i class="fa fa-reply"></i>
              </a>
            </div>
      	</div>
	</div>
	<!-- end: BASIC EXAMPLE -->
</div>

app/views/admin/photo_sliders/show.html.erb
  <div class="wrap-content container" id="container">
    <!-- start: PAGE TITLE -->
    <section id="page-title">
      <div class="row">
        <div class="col-sm-8">
          <h1 class="mainTitle">Photo Slider Data Detail</h1>
          <span class="mainDescription">Halaman untuk melihat detail Photo Slider</span>
        </div>
        <ol class="breadcrumb">
          <li>
            <span>Photo Slider View</span>
          </li>
          <li class="active">
            <span>View Photo Slider</span>
          </li>
        </ol>
      </div>
    </section>
    <!-- end: PAGE TITLE -->
    <!-- start: BASIC EXAMPLE -->
    <div class="container-fluid container-fullw bg-white">
      <div class="row">
        <div class="col-md-12">
          <div class="row">
            <div class="col-lg-8 col-md-12">
              <div class="panel panel-white">
                <div class="panel-heading">
                  <h5 class="panel-title">Detail Photo Slider</h5>
                </div>
                <div class="panel-body">
                  <table class="table">
                    <tbody>
                      
                      <tr>
                        <td>Id</td>
                        <td><%= @photo_slider.id %></td>
                      </tr>
                      <tr>
                        <td>Tittle</td>
                        <td><%= @photo_slider.tittle %></td>
                      </tr>
                      <tr>
                        <td>Description</td>
                        <td><%= @photo_slider.description %></td>
                      </tr>
                      <tr>
                        <td>Image</td>
                        <%= @photo_slider.image.url(:thumb) %>
                        <td><img class="transparent-logo" src="<%= @photo_slider.image.url(:thumb) %>" alt="Boutique"></td>
                      </tr>
                      <tr>
                        <td>Created At</td>
                        <td><%= @photo_slider.created_at %></td>
                      </tr>
                      <tr>
                        <td>Update At</td>
                        <td><%= @photo_slider.updated_at %></td>
                      </tr>

                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12 space20">
          <a href="/admin/photo_sliders/<%= params[:id] %>/edit" class="btn btn-warning">
            Edit <i class="fa fa-edit"></i>
          </a>
          <a href="/admin/photo_sliders" class="btn btn-info">
            Back <i class="fa fa-reply"></i>
          </a>
        </div>
    </div>     

    </div>
    <!-- end: BASIC EXAMPLE -->

    <!-- start: DYNAMIC TABLE -->
    
  </div>