config/routes.rb
Rails.application.routes.draw do

  root to: "homes#index"
  get 'admins' => 'admins#index', :as => 'admin_root'

  devise_for :users, controllers: {sessions: "users/sessions"} do
    delete 'users/sign_out/:auth_token' => 'sessions#destroy', :as => :destroy_user_session
    get "sign_in" => "sessions#create" # for testing
  end

  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }

  resources :homes

  resources :admins
  namespace :admin do    
    resources :admins
    resources :users
    resources :notes do 
      resources :note_details
    end
    resources :product_types
    resources :products
    resources :photo_sliders
  end

end

app/controllers/admin/product_types_controller.rb
class Admin::ProductTypesController < ApplicationController
	before_filter :authenticate_admin!
	layout "admin"

	def index	
		@product_types = ProductType.all
		#render json: @product_type
	end

	def show
	    @product_type = ProductType.find(params[:id])

	    respond_to do |format|
	      format.html # show.html.erb
	      format.json { render json: @product_type }
	    end
	end

	def new
	    @product_type = ProductType.new

	    respond_to do |format|
	      format.html # new.html.erb
	      format.json { render json: @product_type }
	    end
	end

	def create
	    @product_type = ProductType.new(product_type_params)

	    respond_to do |format|
	      if @product_type.save
	        format.html { redirect_to [:admin,@product_type], notice: 'Product Type was successfully created.' }
	        format.json { render json: @product_type, status: :created, location: @product_type }
	      else
	        format.html { render action: "new" }
	        format.json { render json: @product_type.errors, status: :unprocessable_entity }
	      end
	    end
	end

	def edit
	    @product_type = ProductType.find(params[:id])
	end

	def update
		@product_type = ProductType.find(params[:id])		

	    respond_to do |format|
	      if @product_type.update_attributes(product_type_params)
	        format.html { redirect_to [:admin,@product_type], notice: 'Product Type was successfully updated.' }
	        format.json { head :no_content }
	      else
	        format.html { render action: "edit" }
	        format.json { render json: @product_type.errors, status: :unprocessable_entity }
	      end
	    end
	end

	def destroy
	    @product_type = ProductType.find(params[:id])
	    @product_type.destroy

	    respond_to do |format|
	      format.html { redirect_to admin_product_types_url }
	      format.json { head :no_content }
	    end
	  end

	private
	
	def product_type_params
	    params.require(:product_type).permit(:name, :description, :created_by, :created_at, :updated_by, :updated_at,)
	end
end

app/helpers/admin/product_types_helper.rb
module Admin::ProductTypesHelper
end

app/views/admin/product_types/_form.html.erb
<%= form_for([:admin, @product_type], html: {class: "form-horizontal"}) do |f| %>
  <% if @product_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product_type.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if params[:action] == "new" %>
    <%= f.hidden_field :created_by, :value => current_admin.id %>
  <% else %>
    <%= f.hidden_field :updated_by, :value => current_admin.id %>
  <% end %>

  <div class="form-group">
    <label class="col-sm-3 control-label">
      Name
    </label>
    <div class="col-sm-7">
      <%= f.text_field :name, class: 'form-control', placeholder: 'Enter Name Product ..' %>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-3 control-label">
      Description
    </label>
    <div class="col-sm-7">
      <%= f.text_area :description, class: 'form-control', placeholder: 'Enter Description Product ..' %>
    </div>
  </div>

  <%= f.hidden_field :user_id, :value => current_admin.id %>  

  <div class="form-group">
    <div class="col-sm-7">
      <button type="submit" class="btn btn-o btn-primary">
        Submit
      </button>

      &nbsp; &nbsp; &nbsp;
      <button class="btn" type="reset">
          <i class="icon-undo bigger-110"></i>
          Reset
      </button>
    </div>

  </div>
<% end %>

<%= content_for :css do %>
  
    <!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->
    <link href="/vendor/bootstrap-touchspin/jquery.bootstrap-touchspin.min.css" rel="stylesheet" media="screen">
    <link href="/vendor/select2/select2.min.css" rel="stylesheet" media="screen">
    <link href="/vendor/bootstrap-datepicker/bootstrap-datepicker3.standalone.min.css" rel="stylesheet" media="screen">
    <link href="/vendor/bootstrap-timepicker/bootstrap-timepicker.min.css" rel="stylesheet" media="screen">
    <!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->
<% end %>

<%= content_for :js do %>
    
    <!-- start: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
    <script src="/vendor/ckeditor/ckeditor.js"></script>
    <script src="/vendor/ckeditor/adapters/jquery.js"></script>
    <script src="/vendor/jquery-validation/jquery.validate.min.js"></script>

    <script src="/vendor/maskedinput/jquery.maskedinput.min.js"></script>
    <script src="/vendor/bootstrap-touchspin/jquery.bootstrap-touchspin.min.js"></script>
    <script src="/vendor/autosize/autosize.min.js"></script>
    <script src="/vendor/selectFx/classie.js"></script>
    <script src="/vendor/selectFx/selectFx.js"></script>
    <script src="/vendor/select2/select2.min.js"></script>
    <script src="/vendor/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
    <script src="/vendor/bootstrap-timepicker/bootstrap-timepicker.min.js"></script>
    <!-- end: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
  
    <!-- start: JavaScript Event Handlers for this page -->
    <script src="/assets/js/form-validation.js"></script>
    <script src="/assets/js/form-elements.js"></script>
    <script>
      jQuery(document).ready(function() {
        Main.init();
        FormValidator.init();
        FormElements.init();
      });
    </script>
<% end %>

app/views/admin/product_types/edit.html.erb
<div class="wrap-content container" id="container">
  <!-- start: PAGE TITLE -->
  <section id="page-title">
    <div class="row">
      <div class="col-sm-8">
        <h1 class="mainTitle">Form Edit Product Type</h1>
      </div>
      <ol class="breadcrumb">
        <li>
          <span>Product Type Forms</span>
        </li>
        <li class="active">
          <span>Form Product Type</span>
        </li>
      </ol>
    </div>
  </section>
  <!-- end: PAGE TITLE -->
  <!-- start: BASIC EXAMPLE -->
  <div class="container-fluid container-fullw bg-white">
    <div class="row">
      <div class="col-md-12">
        <div class="row">
          <div class="col-lg-8 col-md-12">
            <div class="panel panel-white">
              <div class="panel-heading">
                <h5 class="panel-title">Form Edit</h5>
              </div>
              <div class="panel-body">
                <%= render "form" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12 space20">
        <a href="/admin/product_types" class="btn btn-info">
          Back <i class="fa fa-reply"></i>
        </a>
      </div>
    </div>
  </div>
  <!-- end: BASIC EXAMPLE -->
</div>

app/views/admin/product_types/index.html.erb
<div class="wrap-content container" id="container">
<!-- start: PAGE TITLE -->
<section id="page-title">
  <div class="row">
    <div class="col-sm-8">
      <h1 class="mainTitle">Product Type LIST</h1>
      <span class="mainDescription"></span>
    </div>
    <ol class="breadcrumb">
      <li>
        <span>Dashboard</span>
      </li>
      <li class="active">
        <span>Product Type List</span>
      </li>
    </ol>
  </div>
</section>
<!-- end: PAGE TITLE -->            

<div class="clearfix">&nbsp;</div>

<!-- start: DYNAMIC TABLE -->
<div class="container-fluid container-fullw">
  <div class="row">
    <div class="col-md-12">
      <h5 class="over-title margin-bottom-15">List of <span class="text-bold">Product Type</span></h5>
      <div class="row">
        <div class="col-md-6 space20">
          <a href="/admin/product_types/new" class="btn btn-green">
            Add New <i class="fa fa-plus"></i>
          </a>                      
        </div>
      </div>
      <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover table-full-width dataTable no-footer" id="sample_1">
          <thead>
            <tr>
                <th>Nema Product Type</th>                
                <th>Description</th>
                <th>Action</th>                
            </tr>
          </thead>
          <tbody>
            <% @product_types.each do |product_type| %>
              <tr class="note-content-table">
                <td><%= product_type.name %></td>                
                <td><%= product_type.description %></td>
                <td>
                <a href="<%= admin_product_type_path(product_type) %>" class="btn btn-xs btn-default">
                  Show
                </a>
                <a href="<%= edit_admin_product_type_path(product_type) %>" class="btn btn-xs btn-default">
                  Edit
                </a>

                <a data-confirm="Are you sure?" data-method="delete" href="<%= admin_product_type_path(product_type) %>" class="btn btn-xs btn-danger" rel="nofollow">
                  Delete
                </a>
              </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
</div>

<%= content_for :css do %>
<!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->
<link href="/vendor/bootstrap-touchspin/jquery.bootstrap-touchspin.min.css" rel="stylesheet" media="screen">
<link href="/vendor/select2/select2.min.css" rel="stylesheet" media="screen">
<link href="/vendor/bootstrap-datepicker/bootstrap-datepicker3.standalone.min.css" rel="stylesheet" media="screen">
<link href="/vendor/bootstrap-timepicker/bootstrap-timepicker.min.css" rel="stylesheet" media="screen">
<link href="/vendor/DataTables/css/DT_bootstrap.css" rel="stylesheet" media="screen">
<!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->
<% end %>

<%= content_for :js do %>
<!-- start: JavaScript Event Handlers for this page -->
<script src="/vendor/maskedinput/jquery.maskedinput.min.js"></script>
<script src="/vendor/bootstrap-touchspin/jquery.bootstrap-touchspin.min.js"></script>
<script src="/vendor/autosize/autosize.min.js"></script>
<script src="/vendor/selectFx/classie.js"></script>
<script src="/vendor/selectFx/selectFx.js"></script>
<script src="/vendor/select2/select2.min.js"></script>
<script src="/vendor/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
<script src="/vendor/bootstrap-timepicker/bootstrap-timepicker.min.js"></script>
<!-- end: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
<!-- start: JavaScript Event Handlers for this page -->
<script src="/assets/js/form-elements.js"></script>
<script src="/vendor/DataTables/jquery.dataTables.min.js"></script>
<script src="/assets/js/table-data.js"></script>
<script>
    jQuery(document).ready(function() {
        Main.init();
        TableData.init();
        FormElements.init();
    });
</script>
<!-- end: JavaScript Event Handlers for this page -->
<% end %>

app/views/admin/product_types/new.html.erb
<div class="wrap-content container" id="container">
	<!-- start: PAGE TITLE -->
	<section id="page-title">
		<div class="row">
			<div class="col-sm-8">
				<h1 class="mainTitle">Form Tambah Product Type</h1>
				<span class="mainDescription">Form untuk menambah data Product Type yang baru</span>
			</div>
			<ol class="breadcrumb">
				<li>
					<span>Product Type Forms</span>
				</li>
				<li class="active">
					<span>Form Product Type</span>
				</li>
			</ol>
		</div>
	</section>
	<!-- end: PAGE TITLE -->
	<!-- start: BASIC EXAMPLE -->
	<div class="container-fluid container-fullw bg-white">
		<div class="row">
			<div class="col-md-12">
				<div class="row">
					<div class="col-lg-8 col-md-12">
						<div class="panel panel-white">
							<div class="panel-heading">
								<h5 class="panel-title">Form Tambah</h5>
							</div>
							<div class="panel-body">
								<%= render "form" %>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="row">
            <div class="col-md-12 space20">
              <a href="/admin/product_types" class="btn btn-info">
                Back <i class="fa fa-reply"></i>
              </a>
            </div>
      	</div>
	</div>
	<!-- end: BASIC EXAMPLE -->
</div>

app/views/admin/product_types/show.html.erb
  <div class="wrap-content container" id="container">
    <!-- start: PAGE TITLE -->
    <section id="page-title">
      <div class="row">
        <div class="col-sm-8">
          <h1 class="mainTitle">Product Type Data Detail</h1>
          <span class="mainDescription">Halaman untuk melihat detail Product Type</span>
        </div>
        <ol class="breadcrumb">
          <li>
            <span>Product Type View</span>
          </li>
          <li class="active">
            <span>View Product Type</span>
          </li>
        </ol>
      </div>
    </section>
    <!-- end: PAGE TITLE -->
    <!-- start: BASIC EXAMPLE -->
    <div class="container-fluid container-fullw bg-white">
      <div class="row">
        <div class="col-md-12">
          <div class="row">
            <div class="col-lg-8 col-md-12">
              <div class="panel panel-white">
                <div class="panel-heading">
                  <h5 class="panel-title">Detail Product Type</h5>
                </div>
                <div class="panel-body">
                  <table class="table">
                    <tbody>
                      
                      <tr>
                        <td>Id</td>
                        <td><%= @product_type.id %></td>
                      </tr>                                          
                      <tr>
                        <td>Product Type</td>
                        <td><%= @product_type.name %></td>
                      </tr>
                      <tr>
                        <td>Description</td>
                        <td><%= @product_type.description %></td>
                      </tr>                      
                      <tr>
                        <td>Created At</td>
                        <td><%= @product_type.created_at %></td>
                      </tr>
                      <tr>
                        <td>Update At</td>
                        <td><%= @product_type.updated_at %></td>
                      </tr>

                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12 space20">
          <a href="/admin/product_types/<%= params[:id] %>/edit" class="btn btn-warning">
            Edit <i class="fa fa-edit"></i>
          </a>
          <a href="/admin/product_types" class="btn btn-info">
            Back <i class="fa fa-reply"></i>
          </a>
        </div>
    </div>     

    </div>
    <!-- end: BASIC EXAMPLE -->

    <!-- start: DYNAMIC TABLE -->
    
  </div>