config/routes.rb
Rails.application.routes.draw do

  root to: "homes#index"
  get 'admins' => 'admins#index', :as => 'admin_root'

  devise_for :users, controllers: {sessions: "users/sessions"} do
    delete 'users/sign_out/:auth_token' => 'sessions#destroy', :as => :destroy_user_session
    get "sign_in" => "sessions#create" # for testing
  end

  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }

  resources :homes

  resources :admins
  namespace :admin do    
    resources :admins
    resources :users
    resources :notes do 
      resources :note_details
    end
    resources :product_types
    resources :products
    resources :photo_sliders
  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :notes  	
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
  belongs_to :admin
  has_many :note_details
end

app/models/note_detail.rb
class NoteDetail < ActiveRecord::Base
  belongs_to :note	
end

app/models/photo_slider.rb
class PhotoSlider < ActiveRecord::Base
    has_attached_file :image, :styles => { :display => "763x419#", :thumb => "260x190#" }, :default_url => "no-image.jpg",
			:url => '/images/photo/:basename_:style_:id.:extension',
			:path => ":rails_root/public/images/photo/:basename_:style_:id.:extension"

	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_attached_file :photo, :styles => { :display => "763x419#", :thumb => "260x190#" }, :default_url => "no-image.jpg",
	  :url => '/images/photo/:basename_:style_:id.:extension',
	  :path => ":rails_root/public/images/photo/:basename_:style_:id.:extension"

	validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
end

app/models/product_type.rb
class ProductType < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :notes
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
	before_filter :authenticate_admin!
	
	def index
	
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

  layout :layout_by_resource
  
  before_filter :controller_model
  
  protected

  def controller_model
    @months = ["", "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Jul", "Agustus", "September", "Oktober", "November", "Desember"]
    @days = ["Minggu", "Senin", "Selasa", "Rabu", "Kamis", "Jum'at", "Sabtu"]
    @now = Time.now
    #@hostname = "http://telunjuk.wiradipa.com"
  end
  
  def layout_by_resource
    if devise_controller?
      if resource_name == :admin
        "login"
      else
        "user_login"
      end
    else
      "admin"
    end
  end
  
  def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Admin)
      admin_root_path
    elsif resource_or_scope.is_a?(User)
      root_path
    else
      super
    end
  end
  
  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope.to_s == "admin"
      new_admin_session_path
    else
      new_user_session_path
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	
	layout "application"

	def index
		
	end

	def login

	end	
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController 
	def create
    resource = User.find_by_username(params[:username])
    
    result = Hash.news
    if resource
      if params[:version] # new version
        if resource.active != "Active"
          if resource.valid_password?(params[:password])
              if resource.active == "Active"
                result[:status] = "fail"
                result[:message] = "Username is active in different device."
              else
                  resource.update_attributes(:imei => params[:imei], :active => "Active", :status => "1", :version => params[:version])
                  result[:status] = "success"
                  result[:user_id] = resource.id
                  resource.reset_authentication_token!
                  result[:token] = resource.authentication_token
                  result[:stars] = resource.stars
                  result[:fullname] = resource.fullname
                  result[:imei] = resource.imei
                  result[:version] = resource.version
               end
          else
            result[:status] = "fail"
            result[:message] = "Password is not match."
          end
        else
          result[:status] = "fail"
          result[:message] = "Username not active."
        end
      else # old version
        if resource.valid_password?(params[:password])
          if resource.active == "Active"
            result[:status] = "fail"
            result[:message] = "Username is active in different device."
          else
            result[:status] = "success"
            result[:user_id] = resource.id
            resource.reset_authentication_token!
            result[:token] = resource.authentication_token
            result[:stars] = resource.stars
            result[:fullname] = resource.fullname
          end
        else
          result[:status] = "fail"
          result[:message] = "Password is not match."
        end
      end
    else
      result[:status] = "fail"
      result[:message] = "Username is not exist."
    end
   
    render json: result
  end

  def destroy
    user = User.find_by_authentication_token(params[:auth_token])
    user.authentication_token = nil
    user.status = "0"
    user.active = "Non Active"
    result = Hash.new
    if user.save
      result[:status] = "success"
    else
      result[:status] = "fail"
    end

    render json: result
  end
end

app/helpers/admin/admins_helper.rb
module Admin::AdminsHelper
end

app/helpers/admin/note_details_helper.rb
module Admin::NoteDetailsHelper
end

app/helpers/admin/notes_helper.rb
module Admin::NotesHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admin/admins/edit.html.erb
<div class="wrap-content container" id="container">
  <!-- start: PAGE TITLE -->
  <section id="page-title">
    <div class="row">
      <div class="col-sm-8">
        <h1 class="mainTitle">Form Edit Admin</h1>
      </div>
      <ol class="breadcrumb">
        <li>
          <span>Admin Forms</span>
        </li>
        <li class="active">
          <span>Form Admin</span>
        </li>
      </ol>
    </div>
  </section>
  <!-- end: PAGE TITLE -->
  <!-- start: BASIC EXAMPLE -->
  <div class="container-fluid container-fullw bg-white">
    <div class="row">
      <div class="col-md-12">
        <div class="row">
          <div class="col-lg-8 col-md-12">
            <div class="panel panel-white">
              <div class="panel-heading">
                <h5 class="panel-title">Form Edit</h5>
              </div>
              <div class="panel-body">
                <%= render "form" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12 space20">
        <a href="/admin/admins" class="btn btn-info">
          Back <i class="fa fa-reply"></i>
        </a>
      </div>
    </div>
  </div>
  <!-- end: BASIC EXAMPLE -->
</div>

app/views/admin/admins/index.html.erb
<div class="wrap-content container" id="container">
<!-- start: PAGE TITLE -->
<section id="page-title">
  <div class="row">
    <div class="col-sm-8">
      <h1 class="mainTitle">ADMIN LIST</h1>
      <span class="mainDescription"></span>
    </div>
    <ol class="breadcrumb">
      <li>
        <span>Dashboard</span>
      </li>
      <li class="active">
        <span>Admin List</span>
      </li>
    </ol>
  </div>
</section>
<!-- end: PAGE TITLE -->            

<div class="clearfix">&nbsp;</div>

<!-- start: DYNAMIC TABLE -->
<div class="container-fluid container-fullw">
  <div class="row">
    <div class="col-md-12">
      <h5 class="over-title margin-bottom-15">List of <span class="text-bold">admins</span></h5>
      <div class="row">
        <div class="col-md-6 space20">
          <a href="/admin/admins/new" class="btn btn-green">
            Add New <i class="fa fa-plus"></i>
          </a>                      
        </div>
      </div>
      <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover table-full-width dataTable no-footer" id="sample_1">
          <thead>
            <tr>
              	<th>Name</th>
               	<th>Email</th>                               
                <th>Address</th>
                <th>Phone</th>
                <th>Action</th>
            </tr>
          </thead>
          <tbody>
            <% @admins.each do |admin| %>
              <tr class="admin-content-table">
                <td><%= admin.name %></td>
                <td><%= admin.email %></td>
                <td><%= admin.address %></td>                
                <td><%= admin.phone %></td>
                <td>
                <a href="<%= admin_admin_path(admin) %>" class="btn btn-xs btn-default">
                  Show
                </a>
                <a href="<%= edit_admin_admin_path(admin) %>" class="btn btn-xs btn-default">
                  Edit
                </a>

                <a data-confirm="Are you sure?" data-method="delete" href="<%= admin_admin_path(admin) %>" class="btn btn-xs btn-danger" rel="nofollow">
                  Delete
                </a>
              </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
</div>

<%= content_for :css do %>
<!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->
<link href="/vendor/bootstrap-touchspin/jquery.bootstrap-touchspin.min.css" rel="stylesheet" media="screen">
<link href="/vendor/select2/select2.min.css" rel="stylesheet" media="screen">
<link href="/vendor/bootstrap-datepicker/bootstrap-datepicker3.standalone.min.css" rel="stylesheet" media="screen">
<link href="/vendor/bootstrap-timepicker/bootstrap-timepicker.min.css" rel="stylesheet" media="screen">
<link href="/vendor/DataTables/css/DT_bootstrap.css" rel="stylesheet" media="screen">
<!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->
<% end %>

<%= content_for :js do %>
<!-- start: JavaScript Event Handlers for this page -->
<script src="/vendor/maskedinput/jquery.maskedinput.min.js"></script>
<script src="/vendor/bootstrap-touchspin/jquery.bootstrap-touchspin.min.js"></script>
<script src="/vendor/autosize/autosize.min.js"></script>
<script src="/vendor/selectFx/classie.js"></script>
<script src="/vendor/selectFx/selectFx.js"></script>
<script src="/vendor/select2/select2.min.js"></script>
<script src="/vendor/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
<script src="/vendor/bootstrap-timepicker/bootstrap-timepicker.min.js"></script>
<!-- end: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
<!-- start: JavaScript Event Handlers for this page -->
<script src="/assets/js/form-elements.js"></script>
<script src="/vendor/DataTables/jquery.dataTables.min.js"></script>
<script src="/assets/js/table-data.js"></script>
<script>
    jQuery(document).ready(function() {
        Main.init();
        TableData.init();
        FormElements.init();
    });
</script>
<!-- end: JavaScript Event Handlers for this page -->
<% end %>

app/views/admin/admins/new.html.erb
<div class="wrap-content container" id="container">
	<!-- start: PAGE TITLE -->
	<section id="page-title">
		<div class="row">
			<div class="col-sm-8">
				<h1 class="mainTitle">Form Tambah Admin</h1>
				<span class="mainDescription">Form untuk menambah data Admin yang baru</span>
			</div>
			<ol class="breadcrumb">
				<li>
					<span>Admin Forms</span>
				</li>
				<li class="active">
					<span>Form Admin</span>
				</li>
			</ol>
		</div>
	</section>
	<!-- end: PAGE TITLE -->
	<!-- start: BASIC EXAMPLE -->
	<div class="container-fluid container-fullw bg-white">
		<div class="row">
			<div class="col-md-12">
				<div class="row">
					<div class="col-lg-8 col-md-12">
						<div class="panel panel-white">
							<div class="panel-heading">
								<h5 class="panel-title">Form Tambah</h5>
							</div>
							<div class="panel-body">
								<%= render "form" %>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="row">
            <div class="col-md-12 space20">
              <a href="/admin/admins" class="btn btn-info">
                Back <i class="fa fa-reply"></i>
              </a>
            </div>
      	</div>
	</div>
	<!-- end: BASIC EXAMPLE -->
</div>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pojok Kebul</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<!-- Template Name: Clip-Two - Responsive Admin Template build with Twitter Bootstrap 3.x | Author: ClipTheme -->
<!--[if IE 8]><html class="ie8" lang="en"><![endif]-->
<!--[if IE 9]><html class="ie9" lang="en"><![endif]-->
<!--[if !IE]><!-->
<html lang="en">
  <!--<![endif]-->
  <!-- start: HEAD -->
  <!-- start: HEAD -->
  <head>
    <title>Pojok Kebul - Admin Sign In</title>
    <!-- start: META -->
    <!--[if IE]><meta http-equiv='X-UA-Compatible' content="IE=edge,IE=9,IE=8,chrome=1" /><![endif]-->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta content="" name="description" />
    <meta content="" name="author" />
    <!-- end: META -->
    <!-- start: GOOGLE FONTS -->
    <link href="http://fonts.googleapis.com/css?family=Lato:300,400,400italic,600,700|Raleway:300,400,500,600,700|Crete+Round:400italic" rel="stylesheet" type="text/css" />
    <!-- end: GOOGLE FONTS -->
    <!-- start: MAIN CSS -->
    <link rel="stylesheet" href="/vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/vendor/fontawesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="/vendor/themify-icons/themify-icons.min.css">
    <link href="/vendor/animate.css/animate.min.css" rel="stylesheet" media="screen">
    <link href="/vendor/perfect-scrollbar/perfect-scrollbar.min.css" rel="stylesheet" media="screen">
    <link href="/vendor/switchery/switchery.min.css" rel="stylesheet" media="screen">
    <!-- end: MAIN CSS -->
    <!-- start: CLIP-TWO CSS -->
    <link rel="stylesheet" href="/assets/css/styles.css">
    <link rel="stylesheet" href="/assets/css/plugins.css">
    <link rel="stylesheet" href="/assets/css/themes/theme-1.css" id="skin_color" />
    <!-- end: CLIP-TWO CSS -->
    <!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->
    <!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->
  </head>
  <!-- end: HEAD -->
  <!-- start: BODY -->
  <body class="login">
    <!-- start: LOGIN -->
    <div class="row">
      <div class="main-login col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-4 col-md-offset-4">
        <div class="logo margin-top-30 center">        
          <img class="transparent-logo" src="/assets/images/logo_pokeb_resize.png" alt="Boutique">
        </div>
        <!-- start: LOGIN BOX -->
        <div class="box-login">
          
          <%= form_for(resource, :as => resource_name, :url => session_path(resource_name), :html => {:class => 'form-login'}) do |f| %>
            <fieldset>
              <legend>
                Sign in to POKEB admin page
              </legend>
              <p>
                Please enter your name and password to log in.
              </p>

              <%- flash.each do |name, msg| -%>
                <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
              <%- end -%>
              <div class="form-group">
                <span class="input-icon">
                  <%= f.text_field :username, :class => 'form-control', placeholder: "your username .." %>
                  <i class="fa fa-user"></i> </span>
              </div>
              <div class="form-group form-actions">
                <span class="input-icon">
                  <%= f.password_field :password, :class => 'form-control passwor', placeholder: "your pasword .." %>
                  <i class="fa fa-lock"></i>
                  <a class="forgot" href="login_forgot.html">
                    I forgot my password
                  </a> </span>
              </div>
              <div class="form-actions">
                <div class="checkbox clip-check check-primary">
                  <%= f.check_box :remember_me %> <%= f.label :remember_me %>
                  <label for="remember">
                    Keep me signed in
                  </label>
                </div>
                <button type="submit" class="btn btn-primary pull-right">
                  Login <i class="fa fa-arrow-circle-right"></i>
                </button>
              </div>
            </fieldset>
          <% end %>


          <!-- start: COPYRIGHT -->
          <div class="copyright">
            &copy; <span class="current-year"></span><span class="text-bold text-uppercase"> POJOK KEBUL - YUDISTIRA AKBAR</span>. <span>All rights reserved</span>
          </div>
          <!-- end: COPYRIGHT -->
        </div>
        <!-- end: LOGIN BOX -->
      </div>
    </div>
    <!-- end: LOGIN -->
    <!-- start: MAIN JAVASCRIPTS -->
    <script src="/vendor/jquery/jquery.min.js"></script>
    <script src="/vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="/vendor/modernizr/modernizr.js"></script>
    <script src="/vendor/jquery-cookie/jquery.cookie.js"></script>
    <script src="/vendor/perfect-scrollbar/perfect-scrollbar.min.js"></script>
    <script src="/vendor/switchery/switchery.min.js"></script>
    <!-- end: MAIN JAVASCRIPTS -->
    <!-- start: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
    <script src="/vendor/jquery-validation/jquery.validate.min.js"></script>
    <!-- end: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
    <!-- start: CLIP-TWO JAVASCRIPTS -->
    <script src="/assets/js/main.js"></script>
    <!-- start: JavaScript Event Handlers for this page -->
    <script src="/assets/js/login.js"></script>
    <script>
      jQuery(document).ready(function() {
        Main.init();
        Login.init();
      });
    </script>
    <!-- end: JavaScript Event Handlers for this page -->
    <!-- end: CLIP-TWO JAVASCRIPTS -->
  </body>
  <!-- end: BODY -->
</html>

app/views/partial/_sidebar.html.erb
<div class="sidebar app-aside" id="sidebar">
    <div class="sidebar-container perfect-scrollbar">
        <nav>
            <!-- start: SEARCH FORM -->
            <div class="search-form">
                <a class="s-open" href="#">
                    <i class="ti-search"></i>
                </a>
                <form class="navbar-form" role="search">
                    <a class="s-remove" href="#" target=".navbar-form">
                        <i class="ti-close"></i>
                    </a>
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Search...">
                        <button class="btn search-button" type="submit">
                            <i class="ti-search"></i>
                        </button>
                    </div>
                </form>
            </div>
            <!-- end: SEARCH FORM -->
            <!-- start: MAIN NAVIGATION MENU -->
            <div class="navbar-title">
                <span>Main Navigation</span>
            </div>
            <ul class="main-navigation-menu">
                <% if params[:controller] == "admins" %>
                <li class="active open">
                <% else %>
                <li>
                <% end %>
                    <a href="/admins">
                        <div class="item-content">
                            <div class="item-media">
                                <i class="fa fa-home"></i>
                            </div>
                            <div class="item-inner">
                                <span class="title"> Dashboard </span>
                            </div>
                        </div>
                    </a>
                </li>
                <% if admin_signed_in? %>
                    <!-- <li class="active open"></li> -->
                    <% if params[:controller] == "admin/quizzes" %>
                    <li class="active open">
                    <% else %>
                    <li>
                    <% end %>                    
                    </li>


                    <% if params[:controller] == "admin/admins" %>
                    <li class="active open">
                    <% else %>
                    <li>
                    <% end %>
                    <%= link_to admin_admins_path do %>
                        <div class="item-content">
                            <div class="item-media">
                                <i class="fa fa-user-plus "></i>
                            </div>
                            <div class="item-inner">
                                <span class="title"> Admin </span>
                            </div>
                        </div>
                    <% end %>                        
                    </li>

                    <% if params[:controller] == "admin/photo_sliders" %>
                    <li class="active open">
                    <% else %>
                    <li>
                    <% end %>
                    <%= link_to admin_photo_sliders_path do %>
                        <div class="item-content">
                            <div class="item-media">
                                <i class="fa fa-user-plus "></i>
                            </div>
                            <div class="item-inner">
                                <span class="title"> Photo Slider</span>
                            </div>
                        </div>
                    <% end %>                        
                    </li>

                    <% if params[:controller] == "admin/product_types" %>
                    <li class="active open">
                    <% else %>
                    <li>
                    <% end %>
                    <%= link_to admin_product_types_path do %>
                        <div class="item-content">
                                <div class="item-media">
                                    <i class="fa fa-user"></i>
                                </div>
                                <div class="item-inner">
                                    <span class="title"> Product Type </span>
                                </div>
                            </div>
                    <% end %>                 
                    </li>

                    <% if params[:controller] == "admin/products" %>
                    <li class="active open">
                    <% else %>
                    <li>
                    <% end %>
                    <%= link_to admin_products_path do %>
                        <div class="item-content">
                                <div class="item-media">
                                    <i class="fa fa-user"></i>
                                </div>
                                <div class="item-inner">
                                    <span class="title"> Product </span>
                                </div>
                            </div>
                    <% end %>                 
                    </li> 
                                    
                    
                    <% if params[:controller] == "admin/regions" %>
                    <li class="active open">
                    <% else %>
                    <li>
                    <% end %>                    
                    </li>
                <% end %>
            </ul>
            <!-- end: MAIN NAVIGATION MENU -->
        </nav>
    </div>
</div>

app/views/partial/_top_navbar.html.erb
                <header class="navbar navbar-default navbar-static-top">
                    <!-- start: NAVBAR HEADER -->
                    <div class="navbar-header">
                        <a href="#" class="sidebar-mobile-toggler pull-left hidden-md hidden-lg" class="btn btn-navbar sidebar-toggle" data-toggle-class="app-slide-off" data-toggle-target="#app" data-toggle-click-outside="#sidebar">
                            <i class="ti-align-justify"></i>
                        </a>
                        <a class="navbar-brand" href="index.html">
                            POJOK KEBUL
                        </a>
                        <a href="#" class="sidebar-toggler pull-right visible-md visible-lg" data-toggle-class="app-sidebar-closed" data-toggle-target="#app">
                            <i class="ti-align-justify"></i>
                        </a>
                        <a class="pull-right menu-toggler visible-xs-block" id="menu-toggler" data-toggle="collapse" href=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <i class="ti-view-grid"></i>
                        </a>
                    </div>
                    <!-- end: NAVBAR HEADER -->
                    <!-- start: NAVBAR COLLAPSE -->
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-right">
                            <!-- start: USER OPTIONS DROPDOWN -->
                            <li class="dropdown current-user">
                                <a href class="dropdown-toggle" data-toggle="dropdown">
                                    <img src="/assets/missing.png" alt="Peter"> <span class="username"><%= current_admin.username %> <i class="ti-angle-down"></i></i></span>
                                </a>
                                <ul class="dropdown-menu dropdown-dark">
                                    <li>
                                        <a href="pages_user_profile.html">
                                            <i class="fa fa-user"></i>
                                            My Profile
                                        </a>
                                    </li>
                                    <li>
                                        <%= link_to destroy_admin_session_path, method: :delete , data: { confirm: "anda yakin akan keluar?" } do %>
                                        <i class="fa fa-power-off"></i>
                                        Logout
                                    <% end %>
                                    </li>
                                </ul>
                            </li>
                            <!-- end: USER OPTIONS DROPDOWN -->
                        </ul>
                        <!-- start: MENU TOGGLER FOR MOBILE DEVICES -->
                        <div class="close-handle visible-xs-block menu-toggler" data-toggle="collapse" href=".navbar-collapse">
                            <div class="arrow-left"></div>
                            <div class="arrow-right"></div>
                        </div>
                        <!-- end: MENU TOGGLER FOR MOBILE DEVICES -->
                    </div>
                    <a class="dropdown-off-sidebar sidebar-mobile-toggler hidden-md hidden-lg" data-toggle-class="app-offsidebar-open" data-toggle-target="#app" data-toggle-click-outside="#off-sidebar">
                        &nbsp;
                    </a>
                    <!-- end: NAVBAR COLLAPSE -->
                </header>