config/routes.rb
Rails.application.routes.draw do

  root to: "homes#index"
  get 'admins' => 'admins#index', :as => 'admin_root'

  devise_for :users, controllers: {sessions: "users/sessions"} do
    delete 'users/sign_out/:auth_token' => 'sessions#destroy', :as => :destroy_user_session
    get "sign_in" => "sessions#create" # for testing
  end

  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }

  resources :homes

  resources :admins
  namespace :admin do    
    resources :admins
    resources :users
    resources :notes do 
      resources :note_details
    end
    resources :product_types
    resources :products
    resources :photo_sliders
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
	has_attached_file :photo, :styles => { :display => "763x419#", :thumb => "260x190#" }, :default_url => "no-image.jpg",
	  :url => '/images/photo/:basename_:style_:id.:extension',
	  :path => ":rails_root/public/images/photo/:basename_:style_:id.:extension"

	validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
end

app/models/product_type.rb
class ProductType < ActiveRecord::Base
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
	before_filter :authenticate_admin!
	layout "admin"

	def index	
		@products = Product.all
		#render json: @product
	end

	def show
	    @product = Product.find(params[:id])

	    respond_to do |format|
	      format.html # show.html.erb
	      format.json { render json: @product }
	    end
	end

	def new
	    @product = Product.new

	    respond_to do |format|
	      format.html # new.html.erb
	      format.json { render json: @product }
	    end
	end

	def create
	    @product = Product.new(product_params)

	    respond_to do |format|
	      if @product.save
	        format.html { redirect_to [:admin,@product], notice: 'Product was successfully created.' }
	        format.json { render json: @product, status: :created, location: @product }
	      else
	        format.html { render action: "new" }
	        format.json { render json: @product.errors, status: :unprocessable_entity }
	      end
	    end
	end

	def edit
	    @product = Product.find(params[:id])
	end

	def update
		@product = Product.find(params[:id])		

	    respond_to do |format|
	      if @product.update_attributes(product_params)
	        format.html { redirect_to [:admin,@product], notice: 'Product was successfully updated.' }
	        format.json { head :no_content }
	      else
	        format.html { render action: "edit" }
	        format.json { render json: @product.errors, status: :unprocessable_entity }
	      end
	    end
	end

	def destroy
	    @product = Product.find(params[:id])
	    @product.destroy

	    respond_to do |format|
	      format.html { redirect_to admin_products_url }
	      format.json { head :no_content }
	    end
	  end

	private
	
	def product_params
	    params.require(:product).permit(:product_type_id, :distributor_id, :name, :capacity, :nicotin, :flavor, :quantity, :capital, :selling_price, :stock, :photo, :created_by, :created_at, :updated_by, :updated_at,)
	end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_for([:admin, @product], html: {class: "form-horizontal"}) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if params[:action] == "new" %>
    <%= f.hidden_field :created_by, :value => current_admin.id %>
  <% else %>
    <%= f.hidden_field :updated_by, :value => current_admin.id %>
  <% end %>

  <div class="form-group">
    <label class="col-sm-3 control-label">
      Name
    </label>
    <div class="col-sm-7">
      <%= f.text_field :name, class: 'form-control', placeholder: 'Enter Name Product ..' %>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-3 control-label">
      Distributor
    </label>
    <div class="col-sm-7">
      <%= f.text_field :distributor_id, class: 'form-control', placeholder: 'Enter Distributor Product ..' %>
    </div>
  </div>  

  <div class="form-group">
    <label class="col-sm-3 control-label">
      Capacity
    </label>
    <div class="col-sm-7">
      <%= f.text_field :capacity, class: 'form-control', placeholder: 'Enter Capacity Product ..' %>
    </div>
  </div> 

  <div class="form-group">
    <label class="col-sm-3 control-label">
      Nicotin Liquid
    </label>
    <div class="col-sm-7">
      <%= f.text_field :nicotin, class: 'form-control', placeholder: 'Enter Nic Product ..' %>
    </div>
  </div>   

  <div class="form-group">
    <label class="col-sm-3 control-label">
      Flavor
    </label>
    <div class="col-sm-7">
      <%= f.text_field :flavor, class: 'form-control', placeholder: 'Enter Flavor Product ..' %>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-3 control-label">
      Quantity
    </label>
    <div class="col-sm-7">
      <%= f.text_field :quantity, class: 'form-control', placeholder: 'Enter Quantity Product ..' %>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-3 control-label">
      Capital Product
    </label>
    <div class="col-sm-7">
      <%= f.text_field :capital, class: 'form-control', placeholder: 'Enter Quantity Capital ..' %>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-3 control-label">
      Selling Price Product
    </label>
    <div class="col-sm-7">
      <%= f.text_field :selling_price, class: 'form-control', placeholder: 'Enter Selling Price ..' %>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-3 control-label">
      Stock Product
    </label>
    <div class="col-sm-7">
      <%= f.text_field :stock, class: 'form-control', placeholder: 'Enter Stock Product ..' %>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-3 control-label">
      Photo Product
    </label>
    <div class="col-sm-7">
      <%= f.file_field :photo, :style => "width:360px", :class => "form-control" %>
    </div>
  </div>

  <%= f.hidden_field :user_id, :value => current_admin.id %>  

  <div class="form-group">
    <div class="col-sm-7">
      <button type="submit" class="btn btn-o btn-primary">
        Submit
      </button>

      &nbsp; &nbsp; &nbsp;
      <button class="btn" type="reset">
          <i class="icon-undo bigger-110"></i>
          Reset
      </button>
    </div>

  </div>
<% end %>

<%= content_for :css do %>
  
    <!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->
    <link href="/vendor/bootstrap-touchspin/jquery.bootstrap-touchspin.min.css" rel="stylesheet" media="screen">
    <link href="/vendor/select2/select2.min.css" rel="stylesheet" media="screen">
    <link href="/vendor/bootstrap-datepicker/bootstrap-datepicker3.standalone.min.css" rel="stylesheet" media="screen">
    <link href="/vendor/bootstrap-timepicker/bootstrap-timepicker.min.css" rel="stylesheet" media="screen">
    <!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->
<% end %>

<%= content_for :js do %>
    
    <!-- start: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
    <script src="/vendor/ckeditor/ckeditor.js"></script>
    <script src="/vendor/ckeditor/adapters/jquery.js"></script>
    <script src="/vendor/jquery-validation/jquery.validate.min.js"></script>

    <script src="/vendor/maskedinput/jquery.maskedinput.min.js"></script>
    <script src="/vendor/bootstrap-touchspin/jquery.bootstrap-touchspin.min.js"></script>
    <script src="/vendor/autosize/autosize.min.js"></script>
    <script src="/vendor/selectFx/classie.js"></script>
    <script src="/vendor/selectFx/selectFx.js"></script>
    <script src="/vendor/select2/select2.min.js"></script>
    <script src="/vendor/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
    <script src="/vendor/bootstrap-timepicker/bootstrap-timepicker.min.js"></script>
    <!-- end: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
  
    <!-- start: JavaScript Event Handlers for this page -->
    <script src="/assets/js/form-validation.js"></script>
    <script src="/assets/js/form-elements.js"></script>
    <script>
      jQuery(document).ready(function() {
        Main.init();
        FormValidator.init();
        FormElements.init();
      });
    </script>
<% end %>

app/views/admin/products/edit.html.erb
<div class="wrap-content container" id="container">
  <!-- start: PAGE TITLE -->
  <section id="page-title">
    <div class="row">
      <div class="col-sm-8">
        <h1 class="mainTitle">Form Edit Product</h1>
      </div>
      <ol class="breadcrumb">
        <li>
          <span>Product Forms</span>
        </li>
        <li class="active">
          <span>Form Product</span>
        </li>
      </ol>
    </div>
  </section>
  <!-- end: PAGE TITLE -->
  <!-- start: BASIC EXAMPLE -->
  <div class="container-fluid container-fullw bg-white">
    <div class="row">
      <div class="col-md-12">
        <div class="row">
          <div class="col-lg-8 col-md-12">
            <div class="panel panel-white">
              <div class="panel-heading">
                <h5 class="panel-title">Form Edit</h5>
              </div>
              <div class="panel-body">
                <%= render "form" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12 space20">
        <a href="/admin/products" class="btn btn-info">
          Back <i class="fa fa-reply"></i>
        </a>
      </div>
    </div>
  </div>
  <!-- end: BASIC EXAMPLE -->
</div>

app/views/admin/products/index.html.erb
<div class="wrap-content container" id="container">
<!-- start: PAGE TITLE -->
<section id="page-title">
  <div class="row">
    <div class="col-sm-8">
      <h1 class="mainTitle">Product LIST</h1>
      <span class="mainDescription"></span>
    </div>
    <ol class="breadcrumb">
      <li>
        <span>Dashboard</span>
      </li>
      <li class="active">
        <span>Product List</span>
      </li>
    </ol>
  </div>
</section>
<!-- end: PAGE TITLE -->            

<div class="clearfix">&nbsp;</div>

<!-- start: DYNAMIC TABLE -->
<div class="container-fluid container-fullw">
  <div class="row">
    <div class="col-md-12">
      <h5 class="over-title margin-bottom-15">List of <span class="text-bold">Product</span></h5>
      <div class="row">
        <div class="col-md-6 space20">
          <a href="/admin/products/new" class="btn btn-green">
            Add New <i class="fa fa-plus"></i>
          </a>                      
        </div>
      </div>
      <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover table-full-width dataTable no-footer" id="sample_1">
          <thead>
            <tr>
                <th>Neme Product</th>
                <th>Product Type</th>
                <th>Distributor</th>
                <th>Stock</th>
                <th>Action</th>                
            </tr>
          </thead>
          <tbody>
            <% @products.each do |product| %>
              <tr class="note-content-table">
                <td><%= product.name %></td>                
                <td><%= product.product_type_id %></td>
                <td><%= product.distributor_id %></td>
                <td><%= product.stock %></td>                
                <td>
                <a href="<%= admin_product_path(product) %>" class="btn btn-xs btn-default">
                  Show
                </a>
                <a href="<%= edit_admin_product_path(product) %>" class="btn btn-xs btn-default">
                  Edit
                </a>

                <a data-confirm="Are you sure?" data-method="delete" href="<%= admin_product_path(product) %>" class="btn btn-xs btn-danger" rel="nofollow">
                  Delete
                </a>
              </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
</div>

<%= content_for :css do %>
<!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->
<link href="/vendor/bootstrap-touchspin/jquery.bootstrap-touchspin.min.css" rel="stylesheet" media="screen">
<link href="/vendor/select2/select2.min.css" rel="stylesheet" media="screen">
<link href="/vendor/bootstrap-datepicker/bootstrap-datepicker3.standalone.min.css" rel="stylesheet" media="screen">
<link href="/vendor/bootstrap-timepicker/bootstrap-timepicker.min.css" rel="stylesheet" media="screen">
<link href="/vendor/DataTables/css/DT_bootstrap.css" rel="stylesheet" media="screen">
<!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->
<% end %>

<%= content_for :js do %>
<!-- start: JavaScript Event Handlers for this page -->
<script src="/vendor/maskedinput/jquery.maskedinput.min.js"></script>
<script src="/vendor/bootstrap-touchspin/jquery.bootstrap-touchspin.min.js"></script>
<script src="/vendor/autosize/autosize.min.js"></script>
<script src="/vendor/selectFx/classie.js"></script>
<script src="/vendor/selectFx/selectFx.js"></script>
<script src="/vendor/select2/select2.min.js"></script>
<script src="/vendor/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
<script src="/vendor/bootstrap-timepicker/bootstrap-timepicker.min.js"></script>
<!-- end: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
<!-- start: JavaScript Event Handlers for this page -->
<script src="/assets/js/form-elements.js"></script>
<script src="/vendor/DataTables/jquery.dataTables.min.js"></script>
<script src="/assets/js/table-data.js"></script>
<script>
    jQuery(document).ready(function() {
        Main.init();
        TableData.init();
        FormElements.init();
    });
</script>
<!-- end: JavaScript Event Handlers for this page -->
<% end %>

app/views/admin/products/new.html.erb
<div class="wrap-content container" id="container">
	<!-- start: PAGE TITLE -->
	<section id="page-title">
		<div class="row">
			<div class="col-sm-8">
				<h1 class="mainTitle">Form Tambah Product</h1>
				<span class="mainDescription">Form untuk menambah data Product yang baru</span>
			</div>
			<ol class="breadcrumb">
				<li>
					<span>Product Forms</span>
				</li>
				<li class="active">
					<span>Form Product</span>
				</li>
			</ol>
		</div>
	</section>
	<!-- end: PAGE TITLE -->
	<!-- start: BASIC EXAMPLE -->
	<div class="container-fluid container-fullw bg-white">
		<div class="row">
			<div class="col-md-12">
				<div class="row">
					<div class="col-lg-8 col-md-12">
						<div class="panel panel-white">
							<div class="panel-heading">
								<h5 class="panel-title">Form Tambah</h5>
							</div>
							<div class="panel-body">
								<%= render "form" %>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="row">
            <div class="col-md-12 space20">
              <a href="/admin/products" class="btn btn-info">
                Back <i class="fa fa-reply"></i>
              </a>
            </div>
      	</div>
	</div>
	<!-- end: BASIC EXAMPLE -->
</div>

app/views/admin/products/show.html.erb
  <div class="wrap-content container" id="container">
    <!-- start: PAGE TITLE -->
    <section id="page-title">
      <div class="row">
        <div class="col-sm-8">
          <h1 class="mainTitle">Product Data Detail</h1>
          <span class="mainDescription">Halaman untuk melihat detail Product</span>
        </div>
        <ol class="breadcrumb">
          <li>
            <span>Product View</span>
          </li>
          <li class="active">
            <span>View Product</span>
          </li>
        </ol>
      </div>
    </section>
    <!-- end: PAGE TITLE -->
    <!-- start: BASIC EXAMPLE -->
    <div class="container-fluid container-fullw bg-white">
      <div class="row">
        <div class="col-md-12">
          <div class="row">
            <div class="col-lg-8 col-md-12">
              <div class="panel panel-white">
                <div class="panel-heading">
                  <h5 class="panel-title">Detail Product</h5>
                </div>
                <div class="panel-body">
                  <table class="table">
                    <tbody>
                      
                      <tr>
                        <td>Id</td>
                        <td><%= @product.id %></td>
                      </tr
                      <tr>
                        <td>Name Product</td>
                        <td><%= @product.name %></td>
                      </tr>                      
                      <tr>
                        <td>Product Type</td>
                        <td><%= @product.product_type_id %></td>
                      </tr>
                      <tr>
                        <td>Distributor</td>
                        <td><%= @product.distributor_id %></td>
                      </tr>
                      <tr>
                        <td>Capacity</td>
                        <td><%= @product.capacity %>ml</td>
                      </tr>
                      <tr>
                        <td>Nicotin</td>
                        <td><%= @product.nicotin %> Nic</td>
                      </tr>
                      <tr>
                        <td>Flavor</td>
                        <td><%= @product.flavor %></td>
                      </tr>
                      <tr>
                        <td>Quantity</td>
                        <td><%= @product.quantity %></td>
                      </tr>
                      <tr>
                        <td>Capital</td>
                        <td><%= @product.capital %></td>
                      </tr>
                      <tr>
                        <td>Selling Price</td>
                        <td><%= @product.selling_price %></td>
                      </tr>
                      <tr>
                        <td>Stock</td>
                        <td><%= @product.stock %></td>
                      </tr>                                            
                      <tr>
                        <td>Image</td>                        
                        <td><img class="transparent-logo" src="<%= @product.photo.url(:thumb) %>" alt="Boutique"></td>
                      </tr>
                      <tr>
                        <td>Created At</td>
                        <td><%= @product.created_at %></td>
                      </tr>
                      <tr>
                        <td>Update At</td>
                        <td><%= @product.updated_at %></td>
                      </tr>

                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12 space20">
          <a href="/admin/products/<%= params[:id] %>/edit" class="btn btn-warning">
            Edit <i class="fa fa-edit"></i>
          </a>
          <a href="/admin/products" class="btn btn-info">
            Back <i class="fa fa-reply"></i>
          </a>
        </div>
    </div>     

    </div>
    <!-- end: BASIC EXAMPLE -->

    <!-- start: DYNAMIC TABLE -->
    
  </div>